import { Container, Header } from "@/components/shared";

export const metadata = {
  title: "Next Pizza | Оформление заказа",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={"min-h-screen bg-[#f4f1ee]"}>
      <Container>
        <Header
          hasCart={false}
          hasSearch={false}
          className={"border-b-gray-200"}
        ></Header>
        {children}
      </Container>
    </main>
  );
}
